/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import config.Connect;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLDataException;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Habibie Ahmad
 */
public class FormMenu extends javax.swing.JFrame {
    private Connection conn = new Connect().dbConnection();
    Icon iconLogout = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-logout.png"));
    Icon iconError = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-error.png"));
    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        setIconFrame();        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDashboard = new javax.swing.JPanel();
        bDataPertalife = new javax.swing.JPanel();
        tDataPertalife = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bLaporan = new javax.swing.JPanel();
        tLaporan = new javax.swing.JLabel();
        bKinerja = new javax.swing.JPanel();
        tKinerjaKaryawan = new javax.swing.JLabel();
        jpMenu = new javax.swing.JPanel();
        jExt = new javax.swing.JLabel();
        jMin = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        pDataMaster = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jpDataKaryawan = new javax.swing.JPanel();
        countDataKaryawan = new javax.swing.JLabel();
        tjDataKaryawan = new javax.swing.JLabel();
        bjpDataKaryawan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpDataAsuransiIndividu = new javax.swing.JPanel();
        countAsuransiIndividu = new javax.swing.JLabel();
        tjDataAsuransiIndividu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpDataAsuransipensiun = new javax.swing.JPanel();
        jpDataAsuransiPensiun = new javax.swing.JLabel();
        tjDataAsuransiPensiun = new javax.swing.JLabel();
        bjpDataAsuransiPensiun = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpDataAsuransiKumpulan = new javax.swing.JPanel();
        countDataAsuransiKumpulan = new javax.swing.JLabel();
        tjDataAsuransiKumpulan = new javax.swing.JLabel();
        bjpDataAsuransiKumpulan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pLaporan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jpLaporanDataKaryawan = new javax.swing.JPanel();
        tjLaporanDataBarang = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpLaporanAsuransiIndividu = new javax.swing.JPanel();
        tjLaporanAsuransiIndividu = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jpLaporanPensiun = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tjLaporanPensiun = new javax.swing.JLabel();
        pPenilaianKinerjaKaryawan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jpDataPenilaianKinerjaKaryawan = new javax.swing.JPanel();
        countDataPenilaianKinerjaKaryawan = new javax.swing.JLabel();
        tjDataPenilaianKinerjaKaryawan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PERTALIFE");
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jpDashboard.setBackground(new java.awt.Color(0, 153, 153));

        bDataPertalife.setBackground(new java.awt.Color(255, 255, 255));
        bDataPertalife.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDataPertalife.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDataPertalife.setPreferredSize(new java.awt.Dimension(334, 54));
        bDataPertalife.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDataPertalifeMouseClicked(evt);
            }
        });

        tDataPertalife.setBackground(new java.awt.Color(0, 0, 0));
        tDataPertalife.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tDataPertalife.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-master-white.png"))); // NOI18N
        tDataPertalife.setText(" DATA MASTER");

        javax.swing.GroupLayout bDataPertalifeLayout = new javax.swing.GroupLayout(bDataPertalife);
        bDataPertalife.setLayout(bDataPertalifeLayout);
        bDataPertalifeLayout.setHorizontalGroup(
            bDataPertalifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bDataPertalifeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tDataPertalife, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bDataPertalifeLayout.setVerticalGroup(
            bDataPertalifeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bDataPertalifeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tDataPertalife, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asuransi_jiwa_pertalife_pnsurance_logo.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(300, 300));
        jLabel7.setMinimumSize(new java.awt.Dimension(300, 300));

        bLaporan.setBackground(new java.awt.Color(255, 255, 255));
        bLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLaporan.setPreferredSize(new java.awt.Dimension(334, 54));
        bLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLaporanMouseClicked(evt);
            }
        });

        tLaporan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-file.png"))); // NOI18N
        tLaporan.setText(" LAPORAN");

        javax.swing.GroupLayout bLaporanLayout = new javax.swing.GroupLayout(bLaporan);
        bLaporan.setLayout(bLaporanLayout);
        bLaporanLayout.setHorizontalGroup(
            bLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bLaporanLayout.setVerticalGroup(
            bLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bKinerja.setBackground(new java.awt.Color(255, 255, 255));
        bKinerja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bKinerja.setPreferredSize(new java.awt.Dimension(334, 54));
        bKinerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bKinerjaMouseClicked(evt);
            }
        });

        tKinerjaKaryawan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tKinerjaKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-kinerja-karyawan.png"))); // NOI18N
        tKinerjaKaryawan.setText("TRANSAKSI");

        javax.swing.GroupLayout bKinerjaLayout = new javax.swing.GroupLayout(bKinerja);
        bKinerja.setLayout(bKinerjaLayout);
        bKinerjaLayout.setHorizontalGroup(
            bKinerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bKinerjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bKinerjaLayout.setVerticalGroup(
            bKinerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bKinerjaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpDashboardLayout = new javax.swing.GroupLayout(jpDashboard);
        jpDashboard.setLayout(jpDashboardLayout);
        jpDashboardLayout.setHorizontalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDashboardLayout.createSequentialGroup()
                .addGroup(jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bKinerja, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bDataPertalife, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpDashboardLayout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpDashboardLayout.setVerticalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDashboardLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(bDataPertalife, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bKinerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpMenu.setBackground(new java.awt.Color(0, 153, 153));

        jExt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jExt.setForeground(new java.awt.Color(153, 153, 153));
        jExt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExt.setText("X");
        jExt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExtMouseExited(evt);
            }
        });

        jMin.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jMin.setForeground(new java.awt.Color(153, 153, 153));
        jMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMin.setText("-");
        jMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMinMouseExited(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainPanel.setLayout(new java.awt.CardLayout());

        pDataMaster.setBackground(new java.awt.Color(0, 204, 204));
        pDataMaster.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA MASTER");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jpDataKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        jpDataKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataKaryawan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataKaryawanMouseExited(evt);
            }
        });
        jpDataKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countDataKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        countDataKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataKaryawan.add(countDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataKaryawan.setForeground(new java.awt.Color(0, 102, 102));
        tjDataKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataKaryawan.setText("DATA KARYAWAN");
        jpDataKaryawan.add(tjDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        bjpDataKaryawan.setBackground(new java.awt.Color(244, 43, 54));
        bjpDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bjpDataKaryawanLayout = new javax.swing.GroupLayout(bjpDataKaryawan);
        bjpDataKaryawan.setLayout(bjpDataKaryawanLayout);
        bjpDataKaryawanLayout.setHorizontalGroup(
            bjpDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        bjpDataKaryawanLayout.setVerticalGroup(
            bjpDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpDataKaryawan.add(bjpDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-users.png"))); // NOI18N
        jpDataKaryawan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpDataAsuransiIndividu.setBackground(new java.awt.Color(255, 255, 255));
        jpDataAsuransiIndividu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataAsuransiIndividu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataAsuransiIndividu.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataAsuransiIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataAsuransiIndividuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataAsuransiIndividuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataAsuransiIndividuMouseExited(evt);
            }
        });
        jpDataAsuransiIndividu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countAsuransiIndividu.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        countAsuransiIndividu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpDataAsuransiIndividu.add(countAsuransiIndividu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataAsuransiIndividu.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataAsuransiIndividu.setForeground(new java.awt.Color(0, 102, 102));
        tjDataAsuransiIndividu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataAsuransiIndividu.setText("DATA ASURANSI INDIVIDU");
        jpDataAsuransiIndividu.add(tjDataAsuransiIndividu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));
        tjDataAsuransiIndividu.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setBackground(new java.awt.Color(255, 151, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpDataAsuransiIndividu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-penilaian.png"))); // NOI18N
        jpDataAsuransiIndividu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpDataAsuransipensiun.setBackground(new java.awt.Color(255, 255, 255));
        jpDataAsuransipensiun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataAsuransipensiun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataAsuransipensiun.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataAsuransipensiun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataAsuransipensiunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataAsuransipensiunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataAsuransipensiunMouseExited(evt);
            }
        });
        jpDataAsuransipensiun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpDataAsuransiPensiun.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        jpDataAsuransiPensiun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpDataAsuransiPensiun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataAsuransipensiun.add(jpDataAsuransiPensiun, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataAsuransiPensiun.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataAsuransiPensiun.setForeground(new java.awt.Color(0, 102, 102));
        tjDataAsuransiPensiun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataAsuransiPensiun.setText("DATA ASURANSI DANA PENSIUN ");
        jpDataAsuransipensiun.add(tjDataAsuransiPensiun, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        bjpDataAsuransiPensiun.setBackground(new java.awt.Color(244, 43, 54));
        bjpDataAsuransiPensiun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bjpDataAsuransiPensiunLayout = new javax.swing.GroupLayout(bjpDataAsuransiPensiun);
        bjpDataAsuransiPensiun.setLayout(bjpDataAsuransiPensiunLayout);
        bjpDataAsuransiPensiunLayout.setHorizontalGroup(
            bjpDataAsuransiPensiunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        bjpDataAsuransiPensiunLayout.setVerticalGroup(
            bjpDataAsuransiPensiunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpDataAsuransipensiun.add(bjpDataAsuransiPensiun, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-users.png"))); // NOI18N
        jpDataAsuransipensiun.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpDataAsuransiKumpulan.setBackground(new java.awt.Color(255, 255, 255));
        jpDataAsuransiKumpulan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataAsuransiKumpulan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataAsuransiKumpulan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataAsuransiKumpulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataAsuransiKumpulanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataAsuransiKumpulanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataAsuransiKumpulanMouseExited(evt);
            }
        });
        jpDataAsuransiKumpulan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countDataAsuransiKumpulan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        countDataAsuransiKumpulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countDataAsuransiKumpulan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataAsuransiKumpulan.add(countDataAsuransiKumpulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataAsuransiKumpulan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataAsuransiKumpulan.setForeground(new java.awt.Color(0, 102, 102));
        tjDataAsuransiKumpulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataAsuransiKumpulan.setText("DATA ASURANSI KUMPULAN");
        jpDataAsuransiKumpulan.add(tjDataAsuransiKumpulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        bjpDataAsuransiKumpulan.setBackground(new java.awt.Color(244, 43, 54));
        bjpDataAsuransiKumpulan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bjpDataAsuransiKumpulanLayout = new javax.swing.GroupLayout(bjpDataAsuransiKumpulan);
        bjpDataAsuransiKumpulan.setLayout(bjpDataAsuransiKumpulanLayout);
        bjpDataAsuransiKumpulanLayout.setHorizontalGroup(
            bjpDataAsuransiKumpulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        bjpDataAsuransiKumpulanLayout.setVerticalGroup(
            bjpDataAsuransiKumpulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpDataAsuransiKumpulan.add(bjpDataAsuransiKumpulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-users.png"))); // NOI18N
        jpDataAsuransiKumpulan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        javax.swing.GroupLayout pDataMasterLayout = new javax.swing.GroupLayout(pDataMaster);
        pDataMaster.setLayout(pDataMasterLayout);
        pDataMasterLayout.setHorizontalGroup(
            pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataMasterLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pDataMasterLayout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addGap(382, 382, 382))
                    .addGroup(pDataMasterLayout.createSequentialGroup()
                        .addGroup(pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpDataAsuransipensiun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jpDataKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpDataAsuransiIndividu, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jpDataAsuransiKumpulan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pDataMasterLayout.setVerticalGroup(
            pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataMasterLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDataAsuransiIndividu, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jpDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataMasterLayout.createSequentialGroup()
                        .addComponent(jpDataAsuransiKumpulan, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(391, 391, 391))
                    .addGroup(pDataMasterLayout.createSequentialGroup()
                        .addComponent(jpDataAsuransipensiun, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        mainPanel.add(pDataMaster, "card2");

        pLaporan.setBackground(new java.awt.Color(230, 230, 230));
        pLaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pLaporan.setForeground(new java.awt.Color(102, 102, 102));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("LAPORAN");

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(95, 4));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jpLaporanDataKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        jpLaporanDataKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpLaporanDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpLaporanDataKaryawan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpLaporanDataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLaporanDataKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpLaporanDataKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpLaporanDataKaryawanMouseExited(evt);
            }
        });
        jpLaporanDataKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tjLaporanDataBarang.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjLaporanDataBarang.setForeground(new java.awt.Color(244, 43, 54));
        tjLaporanDataBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjLaporanDataBarang.setText("LAPORAN DATA KARYAWAN");
        jpLaporanDataKaryawan.add(tjLaporanDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 200, 25));

        jPanel7.setBackground(new java.awt.Color(244, 43, 54));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpLaporanDataKaryawan.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-report-50.png"))); // NOI18N
        jpLaporanDataKaryawan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpLaporanAsuransiIndividu.setBackground(new java.awt.Color(255, 255, 255));
        jpLaporanAsuransiIndividu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpLaporanAsuransiIndividu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpLaporanAsuransiIndividu.setPreferredSize(new java.awt.Dimension(304, 150));
        jpLaporanAsuransiIndividu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLaporanAsuransiIndividuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpLaporanAsuransiIndividuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpLaporanAsuransiIndividuMouseExited(evt);
            }
        });
        jpLaporanAsuransiIndividu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tjLaporanAsuransiIndividu.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjLaporanAsuransiIndividu.setForeground(new java.awt.Color(255, 151, 2));
        tjLaporanAsuransiIndividu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjLaporanAsuransiIndividu.setText("LAPORAN ASURANSI INDIVIDU");
        jpLaporanAsuransiIndividu.add(tjLaporanAsuransiIndividu, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 210, 25));

        jPanel15.setBackground(new java.awt.Color(255, 151, 2));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpLaporanAsuransiIndividu.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-report-50.png"))); // NOI18N
        jpLaporanAsuransiIndividu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpLaporanPensiun.setBackground(new java.awt.Color(255, 255, 255));
        jpLaporanPensiun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpLaporanPensiun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpLaporanPensiun.setPreferredSize(new java.awt.Dimension(304, 150));
        jpLaporanPensiun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLaporanPensiunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpLaporanPensiunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpLaporanPensiunMouseExited(evt);
            }
        });
        jpLaporanPensiun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(164, 0, 229));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpLaporanPensiun.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-report-50.png"))); // NOI18N
        jpLaporanPensiun.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        tjLaporanPensiun.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjLaporanPensiun.setForeground(new java.awt.Color(164, 0, 229));
        tjLaporanPensiun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjLaporanPensiun.setText("LAPORAN ASURANSI PENSIUN");
        jpLaporanPensiun.add(tjLaporanPensiun, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        javax.swing.GroupLayout pLaporanLayout = new javax.swing.GroupLayout(pLaporan);
        pLaporan.setLayout(pLaporanLayout);
        pLaporanLayout.setHorizontalGroup(
            pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLaporanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pLaporanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pLaporanLayout.createSequentialGroup()
                        .addComponent(jpLaporanDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jpLaporanAsuransiIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jpLaporanPensiun, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLaporanLayout.setVerticalGroup(
            pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLaporanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLaporanDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpLaporanPensiun, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpLaporanAsuransiIndividu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(507, Short.MAX_VALUE))
        );

        mainPanel.add(pLaporan, "card2");

        pPenilaianKinerjaKaryawan.setBackground(new java.awt.Color(230, 230, 230));
        pPenilaianKinerjaKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pPenilaianKinerjaKaryawan.setForeground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("KINERJA KARYAWAN");

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setPreferredSize(new java.awt.Dimension(230, 4));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jpDataPenilaianKinerjaKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        jpDataPenilaianKinerjaKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataPenilaianKinerjaKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataPenilaianKinerjaKaryawan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataPenilaianKinerjaKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataPenilaianKinerjaKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataPenilaianKinerjaKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataPenilaianKinerjaKaryawanMouseExited(evt);
            }
        });
        jpDataPenilaianKinerjaKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countDataPenilaianKinerjaKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        countDataPenilaianKinerjaKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countDataPenilaianKinerjaKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataPenilaianKinerjaKaryawan.add(countDataPenilaianKinerjaKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataPenilaianKinerjaKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataPenilaianKinerjaKaryawan.setForeground(new java.awt.Color(244, 43, 54));
        tjDataPenilaianKinerjaKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataPenilaianKinerjaKaryawan.setText("DATA PENILAIAN KINERJA KARYAWAN");
        jpDataPenilaianKinerjaKaryawan.add(tjDataPenilaianKinerjaKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 230, 25));

        jPanel4.setBackground(new java.awt.Color(244, 43, 54));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpDataPenilaianKinerjaKaryawan.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-kinerja-karyawan-gray.png"))); // NOI18N
        jpDataPenilaianKinerjaKaryawan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        javax.swing.GroupLayout pPenilaianKinerjaKaryawanLayout = new javax.swing.GroupLayout(pPenilaianKinerjaKaryawan);
        pPenilaianKinerjaKaryawan.setLayout(pPenilaianKinerjaKaryawanLayout);
        pPenilaianKinerjaKaryawanLayout.setHorizontalGroup(
            pPenilaianKinerjaKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPenilaianKinerjaKaryawanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pPenilaianKinerjaKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(pPenilaianKinerjaKaryawanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpDataPenilaianKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(646, 646, 646))
        );
        pPenilaianKinerjaKaryawanLayout.setVerticalGroup(
            pPenilaianKinerjaKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPenilaianKinerjaKaryawanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel12)
                .addGap(3, 3, 3)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jpDataPenilaianKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        mainPanel.add(pPenilaianKinerjaKaryawan, "card2");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMin)
                .addGap(18, 18, 18)
                .addComponent(jExt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jExt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jMin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconFrame(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/asuransi_jiwa_pertalife_pnsurance_logo.jpg")));
    }    
    
    private void countDataTable(String table, javax.swing.JLabel text){
        try{
            String sql = "SELECT COUNT(*)FROM "+table+"";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil.next()){
                if(hasil.getString(1).equals("0")){
                    text.setText("0");
                }else if(hasil.getString(1).length()<2){
                    text.setText("00"+hasil.getString(1));
                }else if(hasil.getString(1).length()<3){
                    text.setText("0"+hasil.getString(1));
//                    text.setText("0"+hasil.getString(1));                                    
                }else{
                    text.setText(hasil.getString(1));
                }                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>Count Table"+table+" Gagal ditampilkan</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }        
    
    private void resetButtonMenu(){        
        tDataPertalife.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-master.png")));
        bDataPertalife.setBorder(null);
        bDataPertalife.setBackground(Color.WHITE);
        tDataPertalife.setForeground(Color.black);    
        bLaporan.setBorder(null);
        bLaporan.setBackground(Color.WHITE); 
        tLaporan.setForeground(Color.black);
        bKinerja.setBorder(null);
        bKinerja.setBackground(Color.WHITE); 
        tKinerjaKaryawan.setForeground(Color.black);
    }
    
    private void bDataPertalifeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDataPertalifeMouseClicked
        // TODO add your handling code here:
        resetButtonMenu();
//        countDataTable("jasabarang",countDataJasaBarang);
//        countDataTable("admin",countDataAdmin);
        bDataPertalife.setBackground(Color.BLACK);
        bDataPertalife.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));        
        tDataPertalife.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-master-white.png")));
        tDataPertalife.setForeground(new java.awt.Color(255,255,255));
                
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pDataMaster);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bDataPertalifeMouseClicked

    private void jMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(FormMenu.ICONIFIED);
    }//GEN-LAST:event_jMinMouseClicked

    private void jMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseEntered
        // TODO add your handling code here:
        jMin.setForeground(Color.BLACK);
    }//GEN-LAST:event_jMinMouseEntered

    private void jMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseExited
        // TODO add your handling code here:
        jMin.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jMinMouseExited

    private void jExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExtMouseClicked

    private void jExtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseEntered
        // TODO add your handling code here:
        jExt.setForeground(Color.BLACK);
    }//GEN-LAST:event_jExtMouseEntered

    private void jExtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseExited
        // TODO add your handling code here:
        jExt.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jExtMouseExited

    private void jpDataKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataKaryawanMouseEntered
        // TODO add your handling code here:      
        tjDataKaryawan.setText("<HTML><u>DATA KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpDataKaryawanMouseEntered

    private void jpDataKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataKaryawanMouseExited
        // TODO add your handling code here:
        tjDataKaryawan.setText("DATA KARYAWAN");        
    }//GEN-LAST:event_jpDataKaryawanMouseExited

    private void jpDataAsuransiIndividuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransiIndividuMouseEntered
        // TODO add your handling code here:   
        tjDataAsuransiIndividu.setText("<HTML><u>DATA ASURANSI INDIVIDU</u></HTML>");
    }//GEN-LAST:event_jpDataAsuransiIndividuMouseEntered

    private void jpDataAsuransiIndividuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransiIndividuMouseExited
        // TODO add your handling code here:
        tjDataAsuransiIndividu.setText("DATA ASURANSI INDIVIDU");        
    }//GEN-LAST:event_jpDataAsuransiIndividuMouseExited

    private void jpDataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataKaryawanMouseClicked
        // TODO add your handling code here:
        new FormDataKaryawan().setVisible(true);
    }//GEN-LAST:event_jpDataKaryawanMouseClicked

    private void jpDataAsuransiIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransiIndividuMouseClicked
        // TODO add your handling code here:
        new FormAsuransiIndividu().setVisible(true);
    }//GEN-LAST:event_jpDataAsuransiIndividuMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void jpDataAsuransipensiunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransipensiunMouseClicked
        // TODO add your handling code here:
         new FormAsuransiPensiun().setVisible(true);
    }//GEN-LAST:event_jpDataAsuransipensiunMouseClicked

    private void jpDataAsuransipensiunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransipensiunMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jpDataAsuransipensiunMouseEntered

    private void jpDataAsuransipensiunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransipensiunMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpDataAsuransipensiunMouseExited

    private void jpDataAsuransiKumpulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransiKumpulanMouseClicked
        // TODO add your handling code here:
         new FormAsuransiKumpulan().setVisible(true);
    }//GEN-LAST:event_jpDataAsuransiKumpulanMouseClicked

    private void jpDataAsuransiKumpulanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransiKumpulanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpDataAsuransiKumpulanMouseEntered

    private void jpDataAsuransiKumpulanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataAsuransiKumpulanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpDataAsuransiKumpulanMouseExited

    private void bLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLaporanMouseClicked
        // TODO add your handling code here:
       resetButtonMenu();
        bLaporan.setBackground(Color.BLACK);
        bLaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));        
        tLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-file-white.png")));
        tLaporan.setForeground(new java.awt.Color(255,255,255));
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pLaporan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bLaporanMouseClicked

    private void jpLaporanDataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataKaryawanMouseClicked
        // TODO add your handling code here:
        new FormReportDataKaryawan().setVisible(true);
    }//GEN-LAST:event_jpLaporanDataKaryawanMouseClicked

    private void jpLaporanDataKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataKaryawanMouseEntered
        // TODO add your handling code here:
        tjLaporanDataBarang.setText("<HTML><u>LAPORAN DATA KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpLaporanDataKaryawanMouseEntered

    private void jpLaporanDataKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataKaryawanMouseExited
        // TODO add your handling code here:
        tjLaporanDataBarang.setText("LAPORAN DATA KARYAWAN");
    }//GEN-LAST:event_jpLaporanDataKaryawanMouseExited

    private void jpLaporanAsuransiIndividuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanAsuransiIndividuMouseClicked
        // TODO add your handling code here:
        new FormReportAsuransiIndividu().setVisible(true);
    }//GEN-LAST:event_jpLaporanAsuransiIndividuMouseClicked

    private void jpLaporanAsuransiIndividuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanAsuransiIndividuMouseEntered
        // TODO add your handling code here:
        tjLaporanAsuransiIndividu.setText("<HTML><u>LAPORAN DATA NILAI KINERJA</u></HTML>");
    }//GEN-LAST:event_jpLaporanAsuransiIndividuMouseEntered

    private void jpLaporanAsuransiIndividuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanAsuransiIndividuMouseExited
        // TODO add your handling code here:
        tjLaporanAsuransiIndividu.setText("LAPORAN DATA NILAI KINERJA");
    }//GEN-LAST:event_jpLaporanAsuransiIndividuMouseExited

    private void jpLaporanPensiunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanPensiunMouseClicked
        // TODO add your handling code here:
        new FormReportAsuransiPensiun().setVisible(true);
    }//GEN-LAST:event_jpLaporanPensiunMouseClicked

    private void jpLaporanPensiunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanPensiunMouseEntered
        // TODO add your handling code here:
        tjLaporanPensiun.setText("<HTML><u>LAPORAN DATA PENILAIAN KINERJA</u></HTML>");
       tjLaporanPensiun.setText("<HTML><u>KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpLaporanPensiunMouseEntered

    private void jpLaporanPensiunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanPensiunMouseExited
        // TODO add your handling code here:
        tjLaporanPensiun.setText("LAPORAN DATA PENILAIAN KINERJA");
        tjLaporanPensiun.setText("KARYAWAN");
    }//GEN-LAST:event_jpLaporanPensiunMouseExited

    private void bKinerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKinerjaMouseClicked
        
        resetButtonMenu();
        bKinerja.setBackground(Color.BLACK);
        bKinerja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));        
        tKinerjaKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-kinerja-karyawan-white.png")));
        tKinerjaKaryawan.setForeground(new java.awt.Color(255,255,255));
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pPenilaianKinerjaKaryawan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bKinerjaMouseClicked

    private void jpDataPenilaianKinerjaKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataPenilaianKinerjaKaryawanMouseClicked
        // TODO add your handling code here:
        new FormPenilaianKinerjaKaryawan().setVisible(true);
    }//GEN-LAST:event_jpDataPenilaianKinerjaKaryawanMouseClicked

    private void jpDataPenilaianKinerjaKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataPenilaianKinerjaKaryawanMouseEntered
        // TODO add your handling code here:
        tjDataPenilaianKinerjaKaryawan.setText("<HTML><u>DATA PENILAIAN KINERJA KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpDataPenilaianKinerjaKaryawanMouseEntered

    private void jpDataPenilaianKinerjaKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataPenilaianKinerjaKaryawanMouseExited
        // TODO add your handling code here:
        tjDataPenilaianKinerjaKaryawan.setText("DATA PENILAIAN KINERJA KARYAWAN");
    }//GEN-LAST:event_jpDataPenilaianKinerjaKaryawanMouseExited

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {              
                new FormMenu().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bDataPertalife;
    private javax.swing.JPanel bKinerja;
    private javax.swing.JPanel bLaporan;
    private javax.swing.JPanel bjpDataAsuransiKumpulan;
    private javax.swing.JPanel bjpDataAsuransiPensiun;
    private javax.swing.JPanel bjpDataKaryawan;
    private javax.swing.JLabel countAsuransiIndividu;
    private javax.swing.JLabel countDataAsuransiKumpulan;
    private javax.swing.JLabel countDataKaryawan;
    private javax.swing.JLabel countDataPenilaianKinerjaKaryawan;
    private javax.swing.JLabel jExt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jMin;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jpDashboard;
    private javax.swing.JPanel jpDataAsuransiIndividu;
    private javax.swing.JPanel jpDataAsuransiKumpulan;
    private javax.swing.JLabel jpDataAsuransiPensiun;
    private javax.swing.JPanel jpDataAsuransipensiun;
    private javax.swing.JPanel jpDataKaryawan;
    private javax.swing.JPanel jpDataPenilaianKinerjaKaryawan;
    private javax.swing.JPanel jpLaporanAsuransiIndividu;
    private javax.swing.JPanel jpLaporanDataKaryawan;
    private javax.swing.JPanel jpLaporanPensiun;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pDataMaster;
    private javax.swing.JPanel pLaporan;
    private javax.swing.JPanel pPenilaianKinerjaKaryawan;
    private javax.swing.JLabel tDataPertalife;
    private javax.swing.JLabel tKinerjaKaryawan;
    private javax.swing.JLabel tLaporan;
    private javax.swing.JLabel tjDataAsuransiIndividu;
    private javax.swing.JLabel tjDataAsuransiKumpulan;
    private javax.swing.JLabel tjDataAsuransiPensiun;
    private javax.swing.JLabel tjDataKaryawan;
    private javax.swing.JLabel tjDataPenilaianKinerjaKaryawan;
    private javax.swing.JLabel tjLaporanAsuransiIndividu;
    private javax.swing.JLabel tjLaporanDataBarang;
    private javax.swing.JLabel tjLaporanPensiun;
    // End of variables declaration//GEN-END:variables
}
