/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import config.Connect;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLDataException;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author  Habibie Ahmad
 */
public class FormMenu extends javax.swing.JFrame {
    private Connection conn = new Connect().dbConnection();
    Icon iconLogout = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-logout.png"));
    Icon iconError = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-error.png"));
    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        setIconFrame();        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDashboard = new javax.swing.JPanel();
        bDataToko = new javax.swing.JPanel();
        tDataToko = new javax.swing.JLabel();
        bKinerja = new javax.swing.JPanel();
        tKinerjaKaryawan = new javax.swing.JLabel();
        bLaporan = new javax.swing.JPanel();
        tLaporan = new javax.swing.JLabel();
        bInfo = new javax.swing.JPanel();
        tInfo = new javax.swing.JLabel();
        bLogout = new javax.swing.JPanel();
        tLogout = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpMenu = new javax.swing.JPanel();
        jExt = new javax.swing.JLabel();
        jMin = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        pDataMaster = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jpDataKaryawan = new javax.swing.JPanel();
        countDataKaryawan = new javax.swing.JLabel();
        tjDataKaryawan = new javax.swing.JLabel();
        bjpDataKaryawan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpDataNilaiKinerja = new javax.swing.JPanel();
        countDataNilaiKinerja = new javax.swing.JLabel();
        tjDataNilaiKinerja = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pPenilaianKinerjaKaryawan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jpDataPenilaianKinerjaKaryawan = new javax.swing.JPanel();
        countDataPenilaianKinerjaKaryawan = new javax.swing.JLabel();
        tjDataPenilaianKinerjaKaryawan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pInfo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jpInfoDev = new javax.swing.JPanel();
        iconInfoDev = new javax.swing.JLabel();
        tjInfoDev = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pLaporan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jpLaporanDataKaryawan = new javax.swing.JPanel();
        tjLaporanDataBarang = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpLaporanDataNilaiKinerja = new javax.swing.JPanel();
        tjLaporanDataNilaiKinerja = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jpLaporanDataPenilaianKinerjaKaryawan = new javax.swing.JPanel();
        tjLaporanDataPenilaianKinerjaKaryawan2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tjLaporanDataPenilaianKinerjaKaryawan1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU Pertalife");
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jpDashboard.setBackground(new java.awt.Color(255, 255, 255));

        bDataToko.setBackground(new java.awt.Color(0, 0, 0));
        bDataToko.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDataToko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDataToko.setPreferredSize(new java.awt.Dimension(334, 54));
        bDataToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDataTokoMouseClicked(evt);
            }
        });

        tDataToko.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tDataToko.setForeground(new java.awt.Color(255, 255, 255));
        tDataToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-master-white.png"))); // NOI18N
        tDataToko.setText(" DATA MASTER");

        javax.swing.GroupLayout bDataTokoLayout = new javax.swing.GroupLayout(bDataToko);
        bDataToko.setLayout(bDataTokoLayout);
        bDataTokoLayout.setHorizontalGroup(
            bDataTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bDataTokoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tDataToko, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bDataTokoLayout.setVerticalGroup(
            bDataTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tDataToko, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bKinerja.setBackground(new java.awt.Color(255, 255, 255));
        bKinerja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bKinerja.setPreferredSize(new java.awt.Dimension(334, 54));
        bKinerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bKinerjaMouseClicked(evt);
            }
        });

        tKinerjaKaryawan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tKinerjaKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-kinerja-karyawan.png"))); // NOI18N
        tKinerjaKaryawan.setText(" KINERJA KARYAWAN");

        javax.swing.GroupLayout bKinerjaLayout = new javax.swing.GroupLayout(bKinerja);
        bKinerja.setLayout(bKinerjaLayout);
        bKinerjaLayout.setHorizontalGroup(
            bKinerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bKinerjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bKinerjaLayout.setVerticalGroup(
            bKinerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bKinerjaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bLaporan.setBackground(new java.awt.Color(255, 255, 255));
        bLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLaporan.setPreferredSize(new java.awt.Dimension(334, 54));
        bLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLaporanMouseClicked(evt);
            }
        });

        tLaporan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-file.png"))); // NOI18N
        tLaporan.setText(" LAPORAN");

        javax.swing.GroupLayout bLaporanLayout = new javax.swing.GroupLayout(bLaporan);
        bLaporan.setLayout(bLaporanLayout);
        bLaporanLayout.setHorizontalGroup(
            bLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bLaporanLayout.setVerticalGroup(
            bLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bInfo.setBackground(new java.awt.Color(255, 255, 255));
        bInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bInfo.setPreferredSize(new java.awt.Dimension(334, 54));
        bInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bInfoMouseClicked(evt);
            }
        });

        tInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-info.png"))); // NOI18N
        tInfo.setText(" INFO");

        javax.swing.GroupLayout bInfoLayout = new javax.swing.GroupLayout(bInfo);
        bInfo.setLayout(bInfoLayout);
        bInfoLayout.setHorizontalGroup(
            bInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bInfoLayout.setVerticalGroup(
            bInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bLogout.setBackground(new java.awt.Color(255, 255, 255));
        bLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLogout.setPreferredSize(new java.awt.Dimension(334, 54));
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
        });

        tLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-logout.png"))); // NOI18N
        tLogout.setText(" LOGOUT");

        javax.swing.GroupLayout bLogoutLayout = new javax.swing.GroupLayout(bLogout);
        bLogout.setLayout(bLogoutLayout);
        bLogoutLayout.setHorizontalGroup(
            bLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bLogoutLayout.setVerticalGroup(
            bLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-logo.png"))); // NOI18N

        javax.swing.GroupLayout jpDashboardLayout = new javax.swing.GroupLayout(jpDashboard);
        jpDashboard.setLayout(jpDashboardLayout);
        jpDashboardLayout.setHorizontalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bKinerja, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataToko, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpDashboardLayout.setVerticalGroup(
            jpDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDashboardLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(bDataToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bKinerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));

        jExt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jExt.setForeground(new java.awt.Color(153, 153, 153));
        jExt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExt.setText("X");
        jExt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExtMouseExited(evt);
            }
        });

        jMin.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jMin.setForeground(new java.awt.Color(153, 153, 153));
        jMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMin.setText("-");
        jMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMinMouseExited(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainPanel.setLayout(new java.awt.CardLayout());

        pDataMaster.setBackground(new java.awt.Color(230, 230, 230));
        pDataMaster.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pDataMaster.setForeground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("DATA MASTER");

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jpDataKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        jpDataKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataKaryawan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataKaryawanMouseExited(evt);
            }
        });
        jpDataKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countDataKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        countDataKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataKaryawan.add(countDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataKaryawan.setForeground(new java.awt.Color(244, 43, 54));
        tjDataKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataKaryawan.setText("DATA KARYAWAN");
        jpDataKaryawan.add(tjDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        bjpDataKaryawan.setBackground(new java.awt.Color(244, 43, 54));
        bjpDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout bjpDataKaryawanLayout = new javax.swing.GroupLayout(bjpDataKaryawan);
        bjpDataKaryawan.setLayout(bjpDataKaryawanLayout);
        bjpDataKaryawanLayout.setHorizontalGroup(
            bjpDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        bjpDataKaryawanLayout.setVerticalGroup(
            bjpDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpDataKaryawan.add(bjpDataKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-users.png"))); // NOI18N
        jpDataKaryawan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpDataNilaiKinerja.setBackground(new java.awt.Color(255, 255, 255));
        jpDataNilaiKinerja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataNilaiKinerja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataNilaiKinerja.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataNilaiKinerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataNilaiKinerjaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataNilaiKinerjaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataNilaiKinerjaMouseExited(evt);
            }
        });
        jpDataNilaiKinerja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countDataNilaiKinerja.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        countDataNilaiKinerja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpDataNilaiKinerja.add(countDataNilaiKinerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataNilaiKinerja.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataNilaiKinerja.setForeground(new java.awt.Color(255, 151, 2));
        tjDataNilaiKinerja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataNilaiKinerja.setText("DATA ASURANSI INDIVIDU");
        jpDataNilaiKinerja.add(tjDataNilaiKinerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        jPanel3.setBackground(new java.awt.Color(255, 151, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpDataNilaiKinerja.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-penilaian.png"))); // NOI18N
        jpDataNilaiKinerja.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        javax.swing.GroupLayout pDataMasterLayout = new javax.swing.GroupLayout(pDataMaster);
        pDataMaster.setLayout(pDataMasterLayout);
        pDataMasterLayout.setHorizontalGroup(
            pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataMasterLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(pDataMasterLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDataMasterLayout.createSequentialGroup()
                        .addComponent(jpDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jpDataNilaiKinerja, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(350, 350, 350))
        );
        pDataMasterLayout.setVerticalGroup(
            pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataMasterLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pDataMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDataNilaiKinerja, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jpDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(409, Short.MAX_VALUE))
        );

        mainPanel.add(pDataMaster, "card2");

        pPenilaianKinerjaKaryawan.setBackground(new java.awt.Color(230, 230, 230));
        pPenilaianKinerjaKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pPenilaianKinerjaKaryawan.setForeground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("KINERJA KARYAWAN");

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setPreferredSize(new java.awt.Dimension(230, 4));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jpDataPenilaianKinerjaKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        jpDataPenilaianKinerjaKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpDataPenilaianKinerjaKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataPenilaianKinerjaKaryawan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpDataPenilaianKinerjaKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDataPenilaianKinerjaKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpDataPenilaianKinerjaKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDataPenilaianKinerjaKaryawanMouseExited(evt);
            }
        });
        jpDataPenilaianKinerjaKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countDataPenilaianKinerjaKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        countDataPenilaianKinerjaKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countDataPenilaianKinerjaKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDataPenilaianKinerjaKaryawan.add(countDataPenilaianKinerjaKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjDataPenilaianKinerjaKaryawan.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjDataPenilaianKinerjaKaryawan.setForeground(new java.awt.Color(244, 43, 54));
        tjDataPenilaianKinerjaKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjDataPenilaianKinerjaKaryawan.setText("DATA PENILAIAN KINERJA KARYAWAN");
        jpDataPenilaianKinerjaKaryawan.add(tjDataPenilaianKinerjaKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 230, 25));

        jPanel4.setBackground(new java.awt.Color(244, 43, 54));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpDataPenilaianKinerjaKaryawan.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-kinerja-karyawan-gray.png"))); // NOI18N
        jpDataPenilaianKinerjaKaryawan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        javax.swing.GroupLayout pPenilaianKinerjaKaryawanLayout = new javax.swing.GroupLayout(pPenilaianKinerjaKaryawan);
        pPenilaianKinerjaKaryawan.setLayout(pPenilaianKinerjaKaryawanLayout);
        pPenilaianKinerjaKaryawanLayout.setHorizontalGroup(
            pPenilaianKinerjaKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPenilaianKinerjaKaryawanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pPenilaianKinerjaKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(pPenilaianKinerjaKaryawanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpDataPenilaianKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(646, 646, 646))
        );
        pPenilaianKinerjaKaryawanLayout.setVerticalGroup(
            pPenilaianKinerjaKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPenilaianKinerjaKaryawanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel12)
                .addGap(3, 3, 3)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jpDataPenilaianKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        mainPanel.add(pPenilaianKinerjaKaryawan, "card2");

        pInfo.setBackground(new java.awt.Color(230, 230, 230));
        pInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("INFO");

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setPreferredSize(new java.awt.Dimension(40, 4));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jpInfoDev.setBackground(new java.awt.Color(255, 255, 255));
        jpInfoDev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpInfoDev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpInfoDev.setPreferredSize(new java.awt.Dimension(304, 150));
        jpInfoDev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpInfoDevMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpInfoDevMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpInfoDevMouseExited(evt);
            }
        });
        jpInfoDev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconInfoDev.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        iconInfoDev.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jpInfoDev.add(iconInfoDev, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 160, 35));

        tjInfoDev.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjInfoDev.setForeground(new java.awt.Color(244, 43, 54));
        tjInfoDev.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjInfoDev.setText("INFO DEVELOPER");
        jpInfoDev.add(tjInfoDev, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        jPanel1.setBackground(new java.awt.Color(244, 43, 54));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpInfoDev.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-developer.png"))); // NOI18N
        jpInfoDev.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        javax.swing.GroupLayout pInfoLayout = new javax.swing.GroupLayout(pInfo);
        pInfo.setLayout(pInfoLayout);
        pInfoLayout.setHorizontalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpInfoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addGroup(pInfoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(650, 650, 650))
        );
        pInfoLayout.setVerticalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addGap(3, 3, 3)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jpInfoDev, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        mainPanel.add(pInfo, "card2");

        pLaporan.setBackground(new java.awt.Color(230, 230, 230));
        pLaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        pLaporan.setForeground(new java.awt.Color(102, 102, 102));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("LAPORAN");

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(95, 4));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jpLaporanDataKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        jpLaporanDataKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpLaporanDataKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpLaporanDataKaryawan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpLaporanDataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLaporanDataKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpLaporanDataKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpLaporanDataKaryawanMouseExited(evt);
            }
        });
        jpLaporanDataKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tjLaporanDataBarang.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjLaporanDataBarang.setForeground(new java.awt.Color(244, 43, 54));
        tjLaporanDataBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjLaporanDataBarang.setText("LAPORAN DATA KARYAWAN");
        jpLaporanDataKaryawan.add(tjLaporanDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 200, 25));

        jPanel7.setBackground(new java.awt.Color(244, 43, 54));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpLaporanDataKaryawan.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-report-50.png"))); // NOI18N
        jpLaporanDataKaryawan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpLaporanDataNilaiKinerja.setBackground(new java.awt.Color(255, 255, 255));
        jpLaporanDataNilaiKinerja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpLaporanDataNilaiKinerja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpLaporanDataNilaiKinerja.setPreferredSize(new java.awt.Dimension(304, 150));
        jpLaporanDataNilaiKinerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLaporanDataNilaiKinerjaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpLaporanDataNilaiKinerjaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpLaporanDataNilaiKinerjaMouseExited(evt);
            }
        });
        jpLaporanDataNilaiKinerja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tjLaporanDataNilaiKinerja.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjLaporanDataNilaiKinerja.setForeground(new java.awt.Color(255, 151, 2));
        tjLaporanDataNilaiKinerja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjLaporanDataNilaiKinerja.setText("LAPORAN DATA ASURANSI INDIVIDU");
        jpLaporanDataNilaiKinerja.add(tjLaporanDataNilaiKinerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 210, 25));

        jPanel15.setBackground(new java.awt.Color(255, 151, 2));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpLaporanDataNilaiKinerja.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-report-50.png"))); // NOI18N
        jpLaporanDataNilaiKinerja.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        jpLaporanDataPenilaianKinerjaKaryawan.setBackground(new java.awt.Color(255, 255, 255));
        jpLaporanDataPenilaianKinerjaKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jpLaporanDataPenilaianKinerjaKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpLaporanDataPenilaianKinerjaKaryawan.setPreferredSize(new java.awt.Dimension(304, 150));
        jpLaporanDataPenilaianKinerjaKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLaporanDataPenilaianKinerjaKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpLaporanDataPenilaianKinerjaKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpLaporanDataPenilaianKinerjaKaryawanMouseExited(evt);
            }
        });
        jpLaporanDataPenilaianKinerjaKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tjLaporanDataPenilaianKinerjaKaryawan2.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjLaporanDataPenilaianKinerjaKaryawan2.setForeground(new java.awt.Color(164, 0, 229));
        tjLaporanDataPenilaianKinerjaKaryawan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjLaporanDataPenilaianKinerjaKaryawan2.setText("KARYAWAN");
        jpLaporanDataPenilaianKinerjaKaryawan.add(tjLaporanDataPenilaianKinerjaKaryawan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 220, 25));

        jPanel8.setBackground(new java.awt.Color(164, 0, 229));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jpLaporanDataPenilaianKinerjaKaryawan.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7, 108));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-report-50.png"))); // NOI18N
        jpLaporanDataPenilaianKinerjaKaryawan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 50, 50));

        tjLaporanDataPenilaianKinerjaKaryawan1.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 12)); // NOI18N
        tjLaporanDataPenilaianKinerjaKaryawan1.setForeground(new java.awt.Color(164, 0, 229));
        tjLaporanDataPenilaianKinerjaKaryawan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tjLaporanDataPenilaianKinerjaKaryawan1.setText("LAPORAN DATA PENILAIAN KINERJA");
        jpLaporanDataPenilaianKinerjaKaryawan.add(tjLaporanDataPenilaianKinerjaKaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 220, 25));

        javax.swing.GroupLayout pLaporanLayout = new javax.swing.GroupLayout(pLaporan);
        pLaporan.setLayout(pLaporanLayout);
        pLaporanLayout.setHorizontalGroup(
            pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLaporanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pLaporanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pLaporanLayout.createSequentialGroup()
                        .addComponent(jpLaporanDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jpLaporanDataNilaiKinerja, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jpLaporanDataPenilaianKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLaporanLayout.setVerticalGroup(
            pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLaporanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLaporanDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpLaporanDataPenilaianKinerjaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpLaporanDataNilaiKinerja, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(409, Short.MAX_VALUE))
        );

        mainPanel.add(pLaporan, "card2");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMin)
                .addGap(18, 18, 18)
                .addComponent(jExt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jExt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jMin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconFrame(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon-logo.png")));
    }    
    
    private void countDataTable(String table, javax.swing.JLabel text){
        try{
            String sql = "SELECT COUNT(*)FROM "+table+"";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil.next()){
                if(hasil.getString(1).equals("0")){
                    text.setText("0");
                }else if(hasil.getString(1).length()<2){
                    text.setText("00"+hasil.getString(1));
                }else if(hasil.getString(1).length()<3){
                    text.setText("0"+hasil.getString(1));
//                    text.setText("0"+hasil.getString(1));                                    
                }else{
                    text.setText(hasil.getString(1));
                }                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>Count Table"+table+" Gagal ditampilkan</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }        
    
    private void resetButtonMenu(){        
        tDataToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-master.png")));
        tKinerjaKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-kinerja-karyawan.png")));
        tLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-file.png")));
        tInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-info.png")));
        bDataToko.setBorder(null);
        bKinerja.setBorder(null);
        bLaporan.setBorder(null);
        bInfo.setBorder(null);
        bDataToko.setBackground(Color.WHITE);
        bKinerja.setBackground(Color.WHITE);        
        bLaporan.setBackground(Color.WHITE);        
        bInfo.setBackground(Color.WHITE);        
        tDataToko.setForeground(Color.black);
        tKinerjaKaryawan.setForeground(Color.black);        
        tLaporan.setForeground(Color.black);        
        tInfo.setForeground(Color.black);        
    }
    
    private void bDataTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDataTokoMouseClicked
        // TODO add your handling code here:
        resetButtonMenu();
//        countDataTable("jasabarang",countDataJasaBarang);
//        countDataTable("admin",countDataAdmin);
        bDataToko.setBackground(Color.BLACK);
        bDataToko.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));        
        tDataToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-data-master-white.png")));
        tDataToko.setForeground(new java.awt.Color(255,255,255));
                
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pDataMaster);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bDataTokoMouseClicked

    private void jMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(FormMenu.ICONIFIED);
    }//GEN-LAST:event_jMinMouseClicked

    private void jMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseEntered
        // TODO add your handling code here:
        jMin.setForeground(Color.BLACK);
    }//GEN-LAST:event_jMinMouseEntered

    private void jMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseExited
        // TODO add your handling code here:
        jMin.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jMinMouseExited

    private void jExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jExtMouseClicked

    private void jExtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseEntered
        // TODO add your handling code here:
        jExt.setForeground(Color.BLACK);
    }//GEN-LAST:event_jExtMouseEntered

    private void jExtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseExited
        // TODO add your handling code here:
        jExt.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jExtMouseExited

    private void bKinerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKinerjaMouseClicked
        // TODO add your handling code here:
//        countDataTable("penjualan", countDataPenjualan);
//        countDataTable("pembelian", countDataPembelian);
        resetButtonMenu();
        bKinerja.setBackground(Color.BLACK);
        bKinerja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));        
        tKinerjaKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon-kinerja-karyawan-white.png")));
        tKinerjaKaryawan.setForeground(new java.awt.Color(255,255,255));
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pPenilaianKinerjaKaryawan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bKinerjaMouseClicked

    private void bLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLaporanMouseClicked
        // TODO add your handling code here:
        resetButtonMenu();
        bLaporan.setBackground(Color.BLACK);
        bLaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));        
        tLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-file-white.png")));
        tLaporan.setForeground(new java.awt.Color(255,255,255));
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(pLaporan);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bLaporanMouseClicked

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        // TODO add your handling code here:
        int a;
        bLogout.setBackground(Color.BLACK);
        tLogout.setForeground(Color.WHITE);
        tLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-logout-white.png")));
        a=JOptionPane.showConfirmDialog(null, "<html><p style=\"font-size:11px; width:200px;\">Apakah Anda Ingin Logout ?</p></html>", "Logout Akun", JOptionPane. YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconLogout);
        if(a==JOptionPane.YES_OPTION) {
            dispose();
            new FormLogin().setVisible(true);
        }else{
            bLogout.setBackground(Color.WHITE);
            tLogout.setForeground(Color.BLACK);
            tLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-logout.png")));
            return;
        }
    }//GEN-LAST:event_bLogoutMouseClicked

    private void jpDataKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataKaryawanMouseEntered
        // TODO add your handling code here:      
        tjDataKaryawan.setText("<HTML><u>DATA KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpDataKaryawanMouseEntered

    private void jpDataKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataKaryawanMouseExited
        // TODO add your handling code here:
        tjDataKaryawan.setText("DATA KARYAWAN");        
    }//GEN-LAST:event_jpDataKaryawanMouseExited

    private void jpDataNilaiKinerjaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataNilaiKinerjaMouseEntered
        // TODO add your handling code here:   
        tjDataNilaiKinerja.setText("<HTML><u>DATA ASURANSI INDIVIDU</u></HTML>");
    }//GEN-LAST:event_jpDataNilaiKinerjaMouseEntered

    private void jpDataNilaiKinerjaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataNilaiKinerjaMouseExited
        // TODO add your handling code here:
        tjDataNilaiKinerja.setText("DATA ASURANSI INDIVIDU");        
    }//GEN-LAST:event_jpDataNilaiKinerjaMouseExited

    private void jpDataPenilaianKinerjaKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataPenilaianKinerjaKaryawanMouseEntered
        // TODO add your handling code here:
        tjDataPenilaianKinerjaKaryawan.setText("<HTML><u>DATA PENILAIAN KINERJA KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpDataPenilaianKinerjaKaryawanMouseEntered

    private void jpDataPenilaianKinerjaKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataPenilaianKinerjaKaryawanMouseExited
        // TODO add your handling code here:
        tjDataPenilaianKinerjaKaryawan.setText("DATA PENILAIAN KINERJA KARYAWAN");  
    }//GEN-LAST:event_jpDataPenilaianKinerjaKaryawanMouseExited

    private void jpInfoDevMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInfoDevMouseEntered
        // TODO add your handling code here:
        tjInfoDev.setText("<HTML><u>INFO DEVELOPER</u></HTML>");
    }//GEN-LAST:event_jpInfoDevMouseEntered

    private void jpInfoDevMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInfoDevMouseExited
        // TODO add your handling code here:
        tjInfoDev.setText("INFO DEVELOPER");  
    }//GEN-LAST:event_jpInfoDevMouseExited

    private void jpLaporanDataKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataKaryawanMouseEntered
        // TODO add your handling code here:
        tjLaporanDataBarang.setText("<HTML><u>LAPORAN DATA KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpLaporanDataKaryawanMouseEntered

    private void jpLaporanDataKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataKaryawanMouseExited
        // TODO add your handling code here:
        tjLaporanDataBarang.setText("LAPORAN DATA KARYAWAN");  
    }//GEN-LAST:event_jpLaporanDataKaryawanMouseExited

    private void jpLaporanDataPenilaianKinerjaKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataPenilaianKinerjaKaryawanMouseEntered
        // TODO add your handling code here:
        tjLaporanDataPenilaianKinerjaKaryawan1.setText("<HTML><u>LAPORAN DATA PENILAIAN KINERJA</u></HTML>");
        tjLaporanDataPenilaianKinerjaKaryawan2.setText("<HTML><u>KARYAWAN</u></HTML>");
    }//GEN-LAST:event_jpLaporanDataPenilaianKinerjaKaryawanMouseEntered

    private void jpLaporanDataPenilaianKinerjaKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataPenilaianKinerjaKaryawanMouseExited
        // TODO add your handling code here:
        tjLaporanDataPenilaianKinerjaKaryawan1.setText("LAPORAN DATA PENILAIAN KINERJA");
        tjLaporanDataPenilaianKinerjaKaryawan2.setText("KARYAWAN");
    }//GEN-LAST:event_jpLaporanDataPenilaianKinerjaKaryawanMouseExited

    private void jpDataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataKaryawanMouseClicked
        // TODO add your handling code here:
        new FormDataKaryawan().setVisible(true);
    }//GEN-LAST:event_jpDataKaryawanMouseClicked

    private void jpDataNilaiKinerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataNilaiKinerjaMouseClicked
        // TODO add your handling code here:
        new FormDataNilaiKinerja().setVisible(true);
    }//GEN-LAST:event_jpDataNilaiKinerjaMouseClicked

    private void jpDataPenilaianKinerjaKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDataPenilaianKinerjaKaryawanMouseClicked
        // TODO add your handling code here:
        new FormPenilaianKinerjaKaryawan().setVisible(true);
    }//GEN-LAST:event_jpDataPenilaianKinerjaKaryawanMouseClicked

    private void jpInfoDevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInfoDevMouseClicked
        // TODO add your handling code here:
        new FormInfoDev().setVisible(true);
    }//GEN-LAST:event_jpInfoDevMouseClicked

    private void jpLaporanDataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataKaryawanMouseClicked
        // TODO add your handling code here:
        new FormReportDataKaryawan().setVisible(true);
    }//GEN-LAST:event_jpLaporanDataKaryawanMouseClicked

    private void jpLaporanDataPenilaianKinerjaKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataPenilaianKinerjaKaryawanMouseClicked
        // TODO add your handling code here:
        new FormReportDataPenilaianKinerjaKaryawan().setVisible(true);
    }//GEN-LAST:event_jpLaporanDataPenilaianKinerjaKaryawanMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO dadd your handling code here:        
        countDataTable("karyawan",countDataKaryawan);
        countDataTable("Asuransi_Individu",countDataNilaiKinerja);
        countDataTable("penilaian_kinerja_karyawan",countDataPenilaianKinerjaKaryawan);
    }//GEN-LAST:event_formWindowGainedFocus

    private void jpLaporanDataNilaiKinerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataNilaiKinerjaMouseClicked
        // TODO add your handling code here:
        new FormReportDataNilaiKinerja().setVisible(true);
    }//GEN-LAST:event_jpLaporanDataNilaiKinerjaMouseClicked

    private void jpLaporanDataNilaiKinerjaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataNilaiKinerjaMouseEntered
        // TODO add your handling code here:
        tjLaporanDataNilaiKinerja.setText("<HTML><u>LAPORAN DATA ASURANSI INDIVIDU</u></HTML>");
    }//GEN-LAST:event_jpLaporanDataNilaiKinerjaMouseEntered

    private void jpLaporanDataNilaiKinerjaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLaporanDataNilaiKinerjaMouseExited
        // TODO add your handling code here:
        tjLaporanDataNilaiKinerja.setText("LAPORAN DATA ASURANSI INDIVIDU");
    }//GEN-LAST:event_jpLaporanDataNilaiKinerjaMouseExited

    private void bInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bInfoMouseClicked
        // TODO add your handling code here:
        resetButtonMenu();
        bInfo.setBackground(Color.BLACK);
        bInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-info-white.png")));
        tInfo.setForeground(new java.awt.Color(255,255,255));

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(pInfo);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bInfoMouseClicked

     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {              
                new FormMenu().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bDataToko;
    private javax.swing.JPanel bInfo;
    private javax.swing.JPanel bKinerja;
    private javax.swing.JPanel bLaporan;
    private javax.swing.JPanel bLogout;
    private javax.swing.JPanel bjpDataKaryawan;
    private javax.swing.JLabel countDataKaryawan;
    private javax.swing.JLabel countDataNilaiKinerja;
    private javax.swing.JLabel countDataPenilaianKinerjaKaryawan;
    private javax.swing.JLabel iconInfoDev;
    private javax.swing.JLabel jExt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jpDashboard;
    private javax.swing.JPanel jpDataKaryawan;
    private javax.swing.JPanel jpDataNilaiKinerja;
    private javax.swing.JPanel jpDataPenilaianKinerjaKaryawan;
    private javax.swing.JPanel jpInfoDev;
    private javax.swing.JPanel jpLaporanDataKaryawan;
    private javax.swing.JPanel jpLaporanDataNilaiKinerja;
    private javax.swing.JPanel jpLaporanDataPenilaianKinerjaKaryawan;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pDataMaster;
    private javax.swing.JPanel pInfo;
    private javax.swing.JPanel pLaporan;
    private javax.swing.JPanel pPenilaianKinerjaKaryawan;
    private javax.swing.JLabel tDataToko;
    private javax.swing.JLabel tInfo;
    private javax.swing.JLabel tKinerjaKaryawan;
    private javax.swing.JLabel tLaporan;
    private javax.swing.JLabel tLogout;
    private javax.swing.JLabel tjDataKaryawan;
    private javax.swing.JLabel tjDataNilaiKinerja;
    private javax.swing.JLabel tjDataPenilaianKinerjaKaryawan;
    private javax.swing.JLabel tjInfoDev;
    private javax.swing.JLabel tjLaporanDataBarang;
    private javax.swing.JLabel tjLaporanDataNilaiKinerja;
    private javax.swing.JLabel tjLaporanDataPenilaianKinerjaKaryawan1;
    private javax.swing.JLabel tjLaporanDataPenilaianKinerjaKaryawan2;
    // End of variables declaration//GEN-END:variables
}
