/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import config.Connect;
import config.ScrollBarCustom;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Habibie Ahmad
 */
public class FormPenilaianKinerjaKaryawan extends javax.swing.JFrame {
    private Connection conn = new Connect().dbConnection();
    private DefaultTableModel tabmode;
    Icon iconQuestion = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-question.png"));    
    Icon iconSuccess = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-success.png"));    
    Icon iconError = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-error.png"));    
    String pNip, pNk, pJbtn;
    /**
     * Creates new form FormPesanan
     */
    public FormPenilaianKinerjaKaryawan() {
        initComponents();
        setIconFrame();
        scrollBarUI();
        dataNilaiKinerja();
        dataPenilaianKinerjaKaryawan();
        buttonAwal(true);
        labelDisabled(true);
        kodePenilaian();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tPenilaianKinerjaKaryawan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jExt = new javax.swing.JLabel();
        jMin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKdPenilaian = new javax.swing.JTextField();
        txtNip = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtJabatan = new javax.swing.JTextField();
        jTN1 = new javax.swing.JLabel();
        tn1 = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        pSearch = new javax.swing.JPanel();
        tSearch = new javax.swing.JTextField();
        pS = new javax.swing.JPanel();
        iSearch = new javax.swing.JLabel();
        bPopUpDataCustomer = new javax.swing.JButton();
        jTN2 = new javax.swing.JLabel();
        tn2 = new javax.swing.JTextField();
        jTN3 = new javax.swing.JLabel();
        tn3 = new javax.swing.JTextField();
        jN1 = new javax.swing.JTextField();
        jN2 = new javax.swing.JTextField();
        jN3 = new javax.swing.JTextField();
        txn1 = new javax.swing.JTextField();
        txn2 = new javax.swing.JTextField();
        txn3 = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        txnTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA PESANAN");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tPenilaianKinerjaKaryawan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tPenilaianKinerjaKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "KODE PENILAIAN", "NIP", "NAMA ", "JABATAN", "N1", "N2", "N3", "xN1", "xN2", "xN3", "xNTOTAL"
            }
        ));
        tPenilaianKinerjaKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tPenilaianKinerjaKaryawan.setFocusable(false);
        tPenilaianKinerjaKaryawan.setOpaque(false);
        tPenilaianKinerjaKaryawan.setRowHeight(30);
        tPenilaianKinerjaKaryawan.setRowMargin(2);
        tPenilaianKinerjaKaryawan.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tPenilaianKinerjaKaryawan.getTableHeader().setReorderingAllowed(false);
        tPenilaianKinerjaKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tPenilaianKinerjaKaryawanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tPenilaianKinerjaKaryawan);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExt.setBackground(new java.awt.Color(255, 255, 255));
        jExt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jExt.setForeground(new java.awt.Color(255, 255, 255));
        jExt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExt.setText("X");
        jExt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExtMouseExited(evt);
            }
        });
        jPanel2.add(jExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 20, 26));

        jMin.setBackground(new java.awt.Color(255, 255, 255));
        jMin.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jMin.setForeground(new java.awt.Color(255, 255, 255));
        jMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMin.setText("-");
        jMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMinMouseExited(evt);
            }
        });
        jPanel2.add(jMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 20, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FORM PENILAIAN KINERJA KARYAWAN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 750, 64));

        jLabel1.setText("Kode Penilaian");

        jLabel2.setText("NIP Karyawan");

        jLabel3.setText("Nama Karyawan");

        jLabel4.setText("Jabatan");

        txtNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNipActionPerformed(evt);
            }
        });

        jTN1.setText("Nilai N1");

        bTambah.setBackground(new java.awt.Color(0, 0, 0));
        bTambah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-plus.png"))); // NOI18N
        bTambah.setText(" TAMBAH");
        bTambah.setBorder(null);
        bTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bTambahMouseExited(evt);
            }
        });
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bEdit.setBackground(new java.awt.Color(0, 0, 0));
        bEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bEdit.setForeground(new java.awt.Color(255, 255, 255));
        bEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-edit.png"))); // NOI18N
        bEdit.setText(" UBAH");
        bEdit.setBorder(null);
        bEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bEditMouseExited(evt);
            }
        });
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bHapus.setBackground(new java.awt.Color(0, 0, 0));
        bHapus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-trash.png"))); // NOI18N
        bHapus.setText(" HAPUS");
        bHapus.setBorder(null);
        bHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bHapusMouseExited(evt);
            }
        });
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(0, 0, 0));
        bReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-reset.png"))); // NOI18N
        bReset.setText(" RESET");
        bReset.setBorder(null);
        bReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bResetMouseExited(evt);
            }
        });
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        pSearch.setBackground(new java.awt.Color(0, 0, 0));
        pSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pSearch.setPreferredSize(new java.awt.Dimension(275, 25));
        pSearch.setLayout(null);

        tSearch.setForeground(new java.awt.Color(153, 153, 153));
        tSearch.setText("Search...");
        tSearch.setBorder(null);
        tSearch.setSelectionColor(new java.awt.Color(255, 68, 56));
        tSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tSearchFocusLost(evt);
            }
        });
        tSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSearchKeyPressed(evt);
            }
        });
        pSearch.add(tSearch);
        tSearch.setBounds(5, 0, 250, 25);

        pS.setBackground(new java.awt.Color(255, 255, 255));
        pS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pS.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout pSLayout = new javax.swing.GroupLayout(pS);
        pS.setLayout(pSLayout);
        pSLayout.setHorizontalGroup(
            pSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        pSLayout.setVerticalGroup(
            pSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        pSearch.add(pS);
        pS.setBounds(0, 0, 260, 25);

        iSearch.setBackground(new java.awt.Color(0, 250, 25));
        iSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-search.png"))); // NOI18N
        iSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iSearchMouseExited(evt);
            }
        });
        pSearch.add(iSearch);
        iSearch.setBounds(260, 0, 25, 25);

        bPopUpDataCustomer.setBackground(new java.awt.Color(0, 0, 0));
        bPopUpDataCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-group-white.png"))); // NOI18N
        bPopUpDataCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bPopUpDataCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bPopUpDataCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bPopUpDataCustomerMouseExited(evt);
            }
        });
        bPopUpDataCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPopUpDataCustomerActionPerformed(evt);
            }
        });

        jTN2.setText("Nilai N2");

        jTN3.setText("Nilai N3");

        jN1.setBackground(new java.awt.Color(0, 0, 0));
        jN1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jN1.setForeground(new java.awt.Color(255, 255, 255));
        jN1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jN1.setText("%");
        jN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN1ActionPerformed(evt);
            }
        });

        jN2.setBackground(new java.awt.Color(0, 0, 0));
        jN2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jN2.setForeground(new java.awt.Color(255, 255, 255));
        jN2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jN2.setText("%");
        jN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN2ActionPerformed(evt);
            }
        });

        jN3.setBackground(new java.awt.Color(0, 0, 0));
        jN3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jN3.setForeground(new java.awt.Color(255, 255, 255));
        jN3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jN3.setText("%");
        jN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jN3ActionPerformed(evt);
            }
        });

        bHitung.setBackground(new java.awt.Color(0, 0, 0));
        bHitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bHitung.setForeground(new java.awt.Color(255, 255, 255));
        bHitung.setText("HITUNG");
        bHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bHitungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bHitungMouseExited(evt);
            }
        });
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        txnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKdPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bPopUpDataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTN1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTN2)
                                    .addComponent(jTN3)
                                    .addComponent(tn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jN1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jN2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jN3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKdPenilaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bPopUpDataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconFrame(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon-logo.png")));
    }  
    
    private void dataNilaiKinerja(){
        try{
            Statement stat = conn.createStatement();
            String sqlN1 = "SELECT * FROM Asuransi_Individu WHERE kd_nilai = 'N1'";            
            String sqlN2 = "SELECT * FROM Asuransi_Individu WHERE kd_nilai = 'N2'";            
            String sqlN3 = "SELECT * FROM Asuransi_Individu WHERE kd_nilai = 'N3'";            
            ResultSet rs1 = stat.executeQuery(sqlN1);
            if (rs1.next()) {
                jTN1.setText("Nilai "+rs1.getString("nama_penilaian")+" (N1)");
                jN1.setText(rs1.getInt("nilai_bobot")+"%");
                ResultSet rs2 = stat.executeQuery(sqlN2);
                if (rs2.next()) {
                    jTN2.setText("Nilai "+rs2.getString("nama_penilaian")+" (N2)");
                    jN2.setText(rs2.getInt("nilai_bobot")+"%");
                    ResultSet rs3 = stat.executeQuery(sqlN3);
                    if (rs3.next()) {
                        jTN3.setText("Nilai "+rs3.getString("nama_penilaian")+" (N3)");
                        jN3.setText(rs3.getInt("nilai_bobot")+"%");
                    }
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Kode Penjualan Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }
    
    private void scrollBarUI(){
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        ScrollBarCustom sp2 = new ScrollBarCustom();
        sp2.setOrientation(JScrollBar.HORIZONTAL);        
    }
    
    private void buttonAwal(boolean t){
        bTambah.setEnabled(t);
        bEdit.setEnabled(!t);
        bHapus.setEnabled(!t);
    }
    
    private void labelDisabled(boolean t){
        txtKdPenilaian.setEnabled(!t);
        txtNip.setEnabled(!t);
        txtNama.setEnabled(!t);
        txtJabatan.setEnabled(!t);        
        txn1.setEnabled(!t);        
        txn2.setEnabled(!t);        
        txn3.setEnabled(!t);        
        txnTotal.setEnabled(!t);        
    }
    
    private void kodePenilaian(){
        txtKdPenilaian.setEnabled(false);
        try {
            String sql="SELECT * FROM penilaian_kinerja_karyawan ORDER BY kode_penilaian DESC";
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()) {
                String kp = rs.getString("kode_penilaian").substring(3);
                String AN = "" + (Integer.parseInt(kp) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "0000";}
                else if(AN.length()==2)
                {Nol = "000";}
                else if(AN.length()==3)
                {Nol = "00";}
                else if(AN.length()==4)
                {Nol = "0";}
                else if(AN.length()==5)
                {Nol = "";}
               txtKdPenilaian.setText("KDP" + Nol + AN);
            } else {
               txtKdPenilaian.setText("KDP00001");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Kode Penjualan Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }

    private void reset(){          
        dataPenilaianKinerjaKaryawan();
        buttonAwal(true);
        kodePenilaian();
        labelDisabled(true);                
        txtNip.setText("");
        txtNama.setText("");
        txtJabatan.setText("");
        tn1.setText("");        
        tn2.setText("");        
        tn3.setText("");        
        txn1.setText("");        
        txn2.setText("");        
        txn3.setText("");        
        txnTotal.setText("");        
        tSearch.setText("");        
    }            
    
    public void customerTerpilih(){
        PopUpDataKaryawan pk = new PopUpDataKaryawan();
        pk.penilaian = this;
        txtNip.setText(pNip);
        txtNama.setText(pNk);
        txtJabatan.setText(pJbtn);
    }        
    
    private void dataPenilaianKinerjaKaryawan(){
        Object[] Baris ={"KODE PENILAIAN","NIP","NAMA","JABATAN","N1","N2","N3","xN1","xN2","xN3","xNTotal"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String sql = "SELECT t1.kode_penilaian,t1.nip_karyawan,t2.nama,t2.jabatan,t1.n1,t1.n2,t1.n3,t1.xn1,t1.xn2,t1.xn3,t1.xntotal FROM penilaian_kinerja_karyawan t1 INNER JOIN karyawan t2 ON t1.nip_karyawan = t2.nip ORDER BY t1.xntotal DESC";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),
                    hasil.getString(8),
                    hasil.getString(9),
                    hasil.getString(10),            
                    hasil.getString(11)            
                });
            }
            tPenilaianKinerjaKaryawan.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    
    private void tambahData(){
        String kdp = txtKdPenilaian.getText();
        String nip = txtNip.getText();
        String n1 = tn1.getText();
        String xn1 = txn1.getText();
        String n2 = tn2.getText();
        String xn2 = txn2.getText();
        String n3 = tn3.getText();
        String xn3 = txn3.getText();        
        String total = txnTotal.getText();
        try {
            if(!kdp.equals("") && !nip.equals("") && !n1.equals("") && !n2.equals("") && !n3.equals("") && !total.equals("")){                
                java.sql.Statement stmt = conn.createStatement();                    
                String sql ="INSERT INTO penilaian_kinerja_karyawan VALUES('"+kdp+"','"+nip+"','"+n1+"','"+n2+"','"+n3+"','"+xn1+"','"+xn2+"','"+xn3+"','"+total+"')";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Success!</b><br>Data berhasil ditambahkan.</p></html>","Success!",JOptionPane.INFORMATION_MESSAGE,iconSuccess);                                    
                reset();                    
            }else{
                JOptionPane.showMessageDialog(null, "<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>Tidak boleh ada kolom yang masih belom terisi! Mohon check kembali.", "Failed!", JOptionPane.ERROR_MESSAGE,iconError);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }
    
    private void ubahData(){
        String kdp = txtKdPenilaian.getText();
        String nip = txtNip.getText();
        String n1 = tn1.getText();
        String xn1 = txn1.getText();
        String n2 = tn2.getText();
        String xn2 = txn2.getText();
        String n3 = tn3.getText();
        String xn3 = txn3.getText();        
        String total = txnTotal.getText();
        try {
            if(!kdp.equals("") && !nip.equals("") && !n1.equals("") && !n2.equals("") && !n3.equals("") && !total.equals("")){                
                java.sql.Statement stmt = conn.createStatement();                    
                String sql ="UPDATE penilaian_kinerja_karyawan SET nip_karyawan = '"+nip+"', n1 = '"+n1+"', n2 = '"+n2+"', n3 = '"+n3+"', xn1 = '"+xn1+"', xn2 = '"+xn2+"', xn3 = '"+xn3+"', xntotal = '"+total+"' WHERE kode_penilaian = '"+kdp+"'";
                stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Success!</b><br>Data berhasil diubah.</p></html>","Success!",JOptionPane.INFORMATION_MESSAGE,iconSuccess);
                reset();                    
            }else{
                JOptionPane.showMessageDialog(null, "<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>Nomor Hp Harus Bertuliskan Angka (Dengan Minimal 8 Angka dan Maksimal 13 Angka).</p></html>", "Failed!", JOptionPane.ERROR_MESSAGE,iconError);                                        
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }
    
    private void hapusData(){
        int a;
        String kp = txtKdPenilaian.getText();        
        a=JOptionPane.showConfirmDialog(null, "<html><p style=\"font-size:11px; width:200px;\">Apakah anda yakin ingin menghapus data dengan <b>No. Pesanan : "+kp+"</b> ?</p></html>", "Hapus Data", JOptionPane. YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,iconQuestion);        
        if(a==JOptionPane.YES_OPTION){       
            try{
                String sql = "DELETE FROM penilaian_kinerja_karyawan WHERE kode_penilaian = '"+kp+"'";
                java.sql.Statement stmt = conn.createStatement();
                stmt.executeUpdate(sql);            
                reset();
                JOptionPane.showMessageDialog(null, "<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Success!</b><br>Data <b>Kode Penilaian : "+kp+"</b> Berhasil dihapus.</p></html>","Success!",JOptionPane.INFORMATION_MESSAGE,iconSuccess);
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
            }
        }else {
            return;
        }
    }
    
    private void cariData(){
        String keyword = tSearch.getText();
        Object[] Baris ={"KODE PENILAIAN","NIP","NAMA","JABATAN","N1","N2","N3","xN1","xN2","xN3","xNTotal"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String sql = "SELECT t1.kode_penilaian,t1.nip_karyawan,t2.nama,t2.jabatan,t1.n1,t1.n2,t1.n3,t1.xn1,t1.xn2,t1.xn3,t1.xntotal FROM penilaian_kinerja_karyawan t1 INNER JOIN karyawan t2 ON t1.nip_karyawan = t2.nip WHERE t1.kode_penilaian LIKE '%"+keyword+"%' or t1.nip LIKE '%"+keyword+"%' t2.nama LIKE '%"+keyword+"%' or t2.jabatan LIKE '%"+keyword+"%' ORDER BY t1.xntotal DESC";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),
                    hasil.getString(8),
                    hasil.getString(9),
                    hasil.getString(10),            
                    hasil.getString(11)            
                });
            }
            tPenilaianKinerjaKaryawan.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    
    private void jExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jExtMouseClicked

    private void jExtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseEntered
        // TODO add your handling code here:
        jExt.setForeground(Color.BLACK);
    }//GEN-LAST:event_jExtMouseEntered

    private void jExtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseExited
        // TODO add your handling code here:
        jExt.setForeground(Color.WHITE);
    }//GEN-LAST:event_jExtMouseExited

    private void jMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_jMinMouseClicked

    private void jMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseEntered
        // TODO add your handling code here:
        jMin.setForeground(Color.RED);
    }//GEN-LAST:event_jMinMouseEntered

    private void jMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseExited
        // TODO add your handling code here:
        jMin.setForeground(Color.WHITE);
    }//GEN-LAST:event_jMinMouseExited

    private void bTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTambahMouseEntered
        // TODO add your handling code here:
        bTambah.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_bTambahMouseEntered

    private void bTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTambahMouseExited
        // TODO add your handling code here:
        bTambah.setBackground(Color.BLACK);
    }//GEN-LAST:event_bTambahMouseExited

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        tambahData();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditMouseEntered
        // TODO add your handling code here:
        bEdit.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_bEditMouseEntered

    private void bEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditMouseExited
        // TODO add your handling code here:
        bEdit.setBackground(Color.BLACK);
    }//GEN-LAST:event_bEditMouseExited

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        ubahData();
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHapusMouseEntered
        // TODO add your handling code here:
        bHapus.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_bHapusMouseEntered

    private void bHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHapusMouseExited
        // TODO add your handling code here:
        bHapus.setBackground(Color.BLACK);
    }//GEN-LAST:event_bHapusMouseExited

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bResetMouseEntered
        // TODO add your handling code here:
        bReset.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_bResetMouseEntered

    private void bResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bResetMouseExited
        // TODO add your handling code here:
        bReset.setBackground(Color.BLACK);
    }//GEN-LAST:event_bResetMouseExited

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bResetActionPerformed

    private void tSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSearchFocusGained
        // TODO add your handling code here:
        if(tSearch.getText().equals("Search...")){
            tSearch.setText("");
            tSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tSearchFocusGained

    private void tSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSearchFocusLost
        // TODO add your handling code here:
        if(tSearch.getText().equals("")){
            tSearch.setText("Search...");
            tSearch.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tSearchFocusLost

    private void tSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cariData();
        }
    }//GEN-LAST:event_tSearchKeyPressed

    private void iSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseClicked
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_iSearchMouseClicked

    private void iSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseEntered
        // TODO add your handling code here:
        pSearch.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_iSearchMouseEntered

    private void iSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseExited
        // TODO add your handling code here:
        pSearch.setBackground(Color.BLACK);
    }//GEN-LAST:event_iSearchMouseExited

    private void tPenilaianKinerjaKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tPenilaianKinerjaKaryawanMouseClicked
        // TODO add your handling code here:
        int row = tPenilaianKinerjaKaryawan.getSelectedRow();        
        
        String kp = tabmode.getValueAt(row,0).toString();            
        String nip = tabmode.getValueAt(row,1).toString();
        String nama = tabmode.getValueAt(row,2).toString();
        String jbtn = tabmode.getValueAt(row,3).toString();
        String n1 = tabmode.getValueAt(row,4).toString();
        String n2 = tabmode.getValueAt(row,5).toString();
        String n3 = tabmode.getValueAt(row,6).toString();
        String xn1 = tabmode.getValueAt(row,7).toString();
        String xn2 = tabmode.getValueAt(row,8).toString();
        String xn3 = tabmode.getValueAt(row,9).toString();
        String xntotal = tabmode.getValueAt(row,10).toString();
            
        txtKdPenilaian.setText(kp);
        txtNip.setText(nip);
        txtNama.setText(nama);
        txtJabatan.setText(jbtn);            
        tn1.setText(n1);
        tn2.setText(n2);
        tn3.setText(n3);
        txn1.setText(xn1);
        txn2.setText(xn2);
        txn3.setText(xn3);
        txnTotal.setText(xntotal);                
        buttonAwal(false);
    }//GEN-LAST:event_tPenilaianKinerjaKaryawanMouseClicked

    private void bPopUpDataCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPopUpDataCustomerMouseEntered
        // TODO add your handling code here:
        bPopUpDataCustomer.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_bPopUpDataCustomerMouseEntered

    private void bPopUpDataCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPopUpDataCustomerMouseExited
        // TODO add your handling code here:
        bPopUpDataCustomer.setBackground(Color.BLACK);
    }//GEN-LAST:event_bPopUpDataCustomerMouseExited

    private void bPopUpDataCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPopUpDataCustomerActionPerformed
        // TODO add your handling code here:
        PopUpDataKaryawan dp = new PopUpDataKaryawan();        
        dp.penilaian = this;
        dp.setVisible(true);
        dp.pack();
        dp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        
    }//GEN-LAST:event_bPopUpDataCustomerActionPerformed

    private void txtNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNipActionPerformed

    private void jN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jN1ActionPerformed

    private void jN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jN2ActionPerformed

    private void jN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jN3ActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:        
        String strjN1 = jN1.getText().replace("%", "");        
        String strjN2 = jN2.getText().replace("%", "");        
        String strjN3 = jN3.getText().replace("%", "");        
        double n1,n2,n3,jn1,jn2,jn3,xn1,xn2,xn3,xnTotal;
        n1 = Integer.parseInt(tn1.getText());        
        jn1 = Integer.parseInt(strjN1);        
        xn1 = n1 * (jn1/100);
        String xtn1 = Double.toString(xn1);
        txn1.setText(xtn1);
        n2 = Integer.parseInt(tn2.getText());        
        jn2 = Integer.parseInt(strjN2);        
        xn2 = n2 * (jn2/100);
        String xtn2 = Double.toString(xn2);
        txn2.setText(xtn2);
        n3 = Integer.parseInt(tn3.getText());        
        jn3 = Integer.parseInt(strjN3);        
        xn3 = n3 * (jn3/100);
        String xtn3 = Double.toString(xn3);
        txn3.setText(xtn3);
        xnTotal = xn1 + xn2 + xn3;
        String sxnTotal = Double.toString(xnTotal);
        txnTotal.setText(sxnTotal);
    }//GEN-LAST:event_bHitungActionPerformed

    private void txnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnTotalActionPerformed

    private void bHitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHitungMouseEntered
        // TODO add your handling code here:
        bHitung.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_bHitungMouseEntered

    private void bHitungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHitungMouseExited
        // TODO add your handling code here:
        bHitung.setBackground(Color.BLACK);
    }//GEN-LAST:event_bHitungMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenilaianKinerjaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenilaianKinerjaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenilaianKinerjaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenilaianKinerjaKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenilaianKinerjaKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bPopUpDataCustomer;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel iSearch;
    private javax.swing.JLabel jExt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jMin;
    private javax.swing.JTextField jN1;
    private javax.swing.JTextField jN2;
    private javax.swing.JTextField jN3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jTN1;
    private javax.swing.JLabel jTN2;
    private javax.swing.JLabel jTN3;
    private javax.swing.JPanel pS;
    private javax.swing.JPanel pSearch;
    private javax.swing.JTable tPenilaianKinerjaKaryawan;
    private javax.swing.JTextField tSearch;
    private javax.swing.JTextField tn1;
    private javax.swing.JTextField tn2;
    private javax.swing.JTextField tn3;
    private javax.swing.JTextField txn1;
    private javax.swing.JTextField txn2;
    private javax.swing.JTextField txn3;
    private javax.swing.JTextField txnTotal;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtKdPenilaian;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    // End of variables declaration//GEN-END:variables
}
