/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import config.Connect;
import config.ScrollBarCustom;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Habibie Ahmad
 */
public class FormDataNilaiKinerja extends javax.swing.JFrame {
    private Connection conn = new Connect().dbConnection();
    private DefaultTableModel tabmode;
    Icon iconQuestion = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-question.png"));    
    Icon iconSuccess = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-success.png"));    
    Icon iconError = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-error.png"));        
    /**
     * Creates new form FormDataPenjualan
     */
    public FormDataNilaiKinerja() {
        initComponents();
        setIconFrame();
        scrollBarUI();
        dataNilaiKinerja();
        buttonAwal(true);
        txtKd.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jExt = new javax.swing.JLabel();
        jMin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        bEdit = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tNilaiKinerja = new javax.swing.JTable();
        pSearch = new javax.swing.JPanel();
        tSearch = new javax.swing.JTextField();
        pS = new javax.swing.JPanel();
        iSearch = new javax.swing.JLabel();
        txtKd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNilaiBobot = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA CUSTOMER");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExt.setBackground(new java.awt.Color(255, 255, 255));
        jExt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jExt.setForeground(new java.awt.Color(255, 255, 255));
        jExt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExt.setText("X");
        jExt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExtMouseExited(evt);
            }
        });
        jPanel1.add(jExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 20, 26));

        jMin.setBackground(new java.awt.Color(255, 255, 255));
        jMin.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jMin.setForeground(new java.awt.Color(255, 255, 255));
        jMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMin.setText("-");
        jMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMinMouseExited(evt);
            }
        });
        jPanel1.add(jMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 20, 26));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DATA ASURANSI INDIVIDU");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 530, 64));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Nama Penilaian");

        bEdit.setBackground(new java.awt.Color(0, 0, 0));
        bEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bEdit.setForeground(new java.awt.Color(255, 255, 255));
        bEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-edit.png"))); // NOI18N
        bEdit.setText(" UBAH");
        bEdit.setBorder(null);
        bEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bEditMouseExited(evt);
            }
        });
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(0, 0, 0));
        bReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-reset.png"))); // NOI18N
        bReset.setText(" RESET");
        bReset.setBorder(null);
        bReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bResetMouseExited(evt);
            }
        });
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        tNilaiKinerja.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tNilaiKinerja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "KODE NILAI", "NAMA PENILAIAN", "NILAI BOBOT"
            }
        ));
        tNilaiKinerja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tNilaiKinerja.setFocusable(false);
        tNilaiKinerja.setOpaque(false);
        tNilaiKinerja.setRowHeight(30);
        tNilaiKinerja.setRowMargin(2);
        tNilaiKinerja.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tNilaiKinerja.getTableHeader().setReorderingAllowed(false);
        tNilaiKinerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tNilaiKinerjaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tNilaiKinerja);
        if (tNilaiKinerja.getColumnModel().getColumnCount() > 0) {
            tNilaiKinerja.getColumnModel().getColumn(0).setPreferredWidth(120);
            tNilaiKinerja.getColumnModel().getColumn(1).setPreferredWidth(350);
            tNilaiKinerja.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        pSearch.setBackground(new java.awt.Color(25, 25, 25));
        pSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pSearch.setPreferredSize(new java.awt.Dimension(275, 25));
        pSearch.setLayout(null);

        tSearch.setForeground(new java.awt.Color(153, 153, 153));
        tSearch.setText("Search...");
        tSearch.setBorder(null);
        tSearch.setSelectionColor(new java.awt.Color(255, 68, 56));
        tSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tSearchFocusLost(evt);
            }
        });
        tSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSearchKeyPressed(evt);
            }
        });
        pSearch.add(tSearch);
        tSearch.setBounds(5, 0, 250, 25);

        pS.setBackground(new java.awt.Color(255, 255, 255));
        pS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pS.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout pSLayout = new javax.swing.GroupLayout(pS);
        pS.setLayout(pSLayout);
        pSLayout.setHorizontalGroup(
            pSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        pSLayout.setVerticalGroup(
            pSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        pSearch.add(pS);
        pS.setBounds(0, 0, 260, 25);

        iSearch.setBackground(new java.awt.Color(25, 25, 25));
        iSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-search.png"))); // NOI18N
        iSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iSearchMouseExited(evt);
            }
        });
        pSearch.add(iSearch);
        iSearch.setBounds(260, 0, 25, 25);

        jLabel6.setText("Kode Nilai");

        txtNilaiBobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilaiBobotActionPerformed(evt);
            }
        });

        jLabel2.setText("Nilai Bobot");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("%");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtNilaiBobot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(189, 189, 189)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtKd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNilaiBobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void setIconFrame(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon-logo.png")));
    }
    
    private void scrollBarUI(){
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());        
        jScrollPane1.setHorizontalScrollBar(sp);
    }
    
    private void buttonAwal(boolean t){           
        bEdit.setEnabled(!t);           
    }
    
    private void ubahData(){
        String kd_nilai = txtKd.getText();
        String nm = txtNama.getText();
        String nb = txtNilaiBobot.getText();    
        try {
            if(!kd_nilai.equals("") && !nm.equals("") && !nb.equals("")){                                                                                                               
                java.sql.Statement stmt = conn.createStatement();
                String sql="UPDATE Asuransi_Individu SET nama_penilaian = '"+nm+"', nilai_bobot = '"+nb+"' WHERE kd_nilai ='"+kd_nilai+"'";                                                
                stmt.executeUpdate(sql);                
                JOptionPane.showMessageDialog(null, "<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Success!</b><br>Data berhasil diubah.</p></html>","Success!",JOptionPane.INFORMATION_MESSAGE,iconSuccess);
                reset();                                    
            }else{
                JOptionPane.showMessageDialog(null, "<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>Tidak boleh ada kolom yang masih belom terisi! Mohon check kembali.", "Failed!", JOptionPane.ERROR_MESSAGE,iconError);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }            
    
    private void cariData(){
        String keyword = tSearch.getText();
        Object[] Baris ={"KODE NILAI","NAMA PENILAIAN","NILAI BOBOT"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String sql = "SELECT * FROM Asuransi_Individu WHERE kd_nilai LIKE '%"+keyword+"%' or nama_penilaian LIKE '%"+keyword+"%' or nilai_bobot LIKE '%"+keyword+"%''";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3)+"%"                    
                });
            }
            tNilaiKinerja.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }                       
    }
    
    private void reset(){
        buttonAwal(true);
        txtKd.setText("");
        txtNama.setText("");
        txtNilaiBobot.setText("");
        tSearch.setText("Search...");         
        dataNilaiKinerja();
    }
    
    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bResetActionPerformed

    private void iSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseEntered
        // TODO add your handling code here:
        pSearch.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_iSearchMouseEntered

    private void iSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseExited
        // TODO add your handling code here:
        pSearch.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_iSearchMouseExited

    private void tSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSearchFocusGained
        // TODO add your handling code here:
        if(tSearch.getText().equals("Search...")){            
            tSearch.setText("");
            tSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tSearchFocusGained

    private void tSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSearchFocusLost
        // TODO add your handling code here:
            if(tSearch.getText().equals("")){            
            tSearch.setText("Search...");
            tSearch.setForeground(new Color(153,153,153));
        }                                   
    }//GEN-LAST:event_tSearchFocusLost

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        ubahData();
    }//GEN-LAST:event_bEditActionPerformed

    private void iSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseClicked
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_iSearchMouseClicked

    private void tSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cariData();
        }
    }//GEN-LAST:event_tSearchKeyPressed

    private void tNilaiKinerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNilaiKinerjaMouseClicked
        // TODO add your handling code here:
        int row = tNilaiKinerja.getSelectedRow();
        String kd_nilai = tabmode.getValueAt(row, 0).toString();
        try {
            String sql="SELECT * FROM Asuransi_Individu WHERE kd_nilai = '"+kd_nilai+"'";
            java.sql.Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            if (rs.next()) {
                txtKd.setText(kd_nilai);
                txtNama.setText(rs.getString("nama_penilaian"));
                txtNilaiBobot.setText(rs.getString("nilai_bobot"));
                buttonAwal(false);
            }else{}
        } catch ( SQLException e){
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }//GEN-LAST:event_tNilaiKinerjaMouseClicked

    private void jMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(FormDataNilaiKinerja.ICONIFIED);
    }//GEN-LAST:event_jMinMouseClicked

    private void jMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseEntered
        // TODO add your handling code here:
        jMin.setForeground(Color.RED);
    }//GEN-LAST:event_jMinMouseEntered

    private void jMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseExited
        // TODO add your handling code here:
        jMin.setForeground(Color.WHITE);
    }//GEN-LAST:event_jMinMouseExited

    private void jExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jExtMouseClicked

    private void jExtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseEntered
        // TODO add your handling code here:
        jExt.setForeground(Color.RED);
    }//GEN-LAST:event_jExtMouseEntered

    private void jExtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseExited
        // TODO add your handling code here:
        jExt.setForeground(Color.WHITE);
    }//GEN-LAST:event_jExtMouseExited

    private void bEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditMouseEntered
        // TODO add your handling code here:
        bEdit.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_bEditMouseEntered

    private void bEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditMouseExited
        // TODO add your handling code here:
        bEdit.setBackground(Color.BLACK);
    }//GEN-LAST:event_bEditMouseExited

    private void bResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bResetMouseEntered
        // TODO add your handling code here:
        bReset.setBackground(new Color(15,15,15));
    }//GEN-LAST:event_bResetMouseEntered

    private void bResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bResetMouseExited
        // TODO add your handling code here:
        bReset.setBackground(Color.BLACK);
    }//GEN-LAST:event_bResetMouseExited

    private void txtNilaiBobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiBobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiBobotActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void dataNilaiKinerja(){
        Object[] Baris ={"KODE NILAI","NAMA PENILAIAN","NILAI BOBOT"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String sql = "SELECT * FROM Asuransi_Individu ORDER BY kd_nilai ASC";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3)+"%"                    
                });
            }            
            tNilaiKinerja.setModel(tabmode);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Table Customer Failed!</b><br>"+e+"</p></html>","Table Customer Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataNilaiKinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataNilaiKinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataNilaiKinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataNilaiKinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataNilaiKinerja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bReset;
    private javax.swing.JLabel iSearch;
    private javax.swing.JLabel jExt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pS;
    private javax.swing.JPanel pSearch;
    private javax.swing.JTable tNilaiKinerja;
    private javax.swing.JTextField tSearch;
    private javax.swing.JTextField txtKd;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilaiBobot;
    // End of variables declaration//GEN-END:variables
}
