/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import config.Connect;
import config.ScrollBarCustom;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Habibie Ahmad
 */
public class PopUpDataKaryawan extends javax.swing.JFrame {
    private Connection conn = new Connect().dbConnection();
    private DefaultTableModel tabmode;
    Icon iconError = new javax.swing.ImageIcon(getClass().getResource("/images/icon-message-error.png"));    
    public FormPenilaianKinerjaKaryawan penilaian = null;
    /**
     * Creates new form DataPenjualan
     */
    public PopUpDataKaryawan() {
        initComponents();
        setIconFrame();
        dataKaryawan();
        scrollBarUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pSearch = new javax.swing.JPanel();
        tSearch = new javax.swing.JTextField();
        pS = new javax.swing.JPanel();
        iSearch = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tKaryawan = new javax.swing.JTable();
        txtPopUp = new javax.swing.JLabel();
        jMin = new javax.swing.JLabel();
        jExt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PopUp Data Jasa Dan Barang");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(567, 311));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        pSearch.setBackground(new java.awt.Color(0, 0, 0));
        pSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pSearch.setForeground(new java.awt.Color(255, 255, 255));
        pSearch.setPreferredSize(new java.awt.Dimension(275, 25));
        pSearch.setLayout(null);

        tSearch.setForeground(new java.awt.Color(153, 153, 153));
        tSearch.setText("Search...");
        tSearch.setBorder(null);
        tSearch.setSelectionColor(new java.awt.Color(255, 68, 56));
        tSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tSearchFocusLost(evt);
            }
        });
        tSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tSearchKeyPressed(evt);
            }
        });
        pSearch.add(tSearch);
        tSearch.setBounds(5, 0, 250, 25);

        pS.setBackground(new java.awt.Color(255, 255, 255));
        pS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pS.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout pSLayout = new javax.swing.GroupLayout(pS);
        pS.setLayout(pSLayout);
        pSLayout.setHorizontalGroup(
            pSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        pSLayout.setVerticalGroup(
            pSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        pSearch.add(pS);
        pS.setBounds(0, 0, 260, 25);

        iSearch.setBackground(new java.awt.Color(0, 0, 0));
        iSearch.setForeground(new java.awt.Color(255, 255, 255));
        iSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-search.png"))); // NOI18N
        iSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iSearchMouseExited(evt);
            }
        });
        pSearch.add(iSearch);
        iSearch.setBounds(260, 0, 25, 25);

        tKaryawan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIP", "NAMA", "JENIS KELAMIN", "TGL LAHIR", "NO. HP", "ALAMAT", "JABATAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tKaryawan.setFocusable(false);
        tKaryawan.setOpaque(false);
        tKaryawan.setRowHeight(30);
        tKaryawan.setRowMargin(2);
        tKaryawan.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tKaryawan.getTableHeader().setReorderingAllowed(false);
        tKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tKaryawan);
        if (tKaryawan.getColumnModel().getColumnCount() > 0) {
            tKaryawan.getColumnModel().getColumn(0).setPreferredWidth(75);
            tKaryawan.getColumnModel().getColumn(1).setPreferredWidth(160);
            tKaryawan.getColumnModel().getColumn(2).setPreferredWidth(5);
            tKaryawan.getColumnModel().getColumn(3).setPreferredWidth(45);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPopUp)
                .addGap(126, 533, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPopUp)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        jMin.setBackground(new java.awt.Color(255, 255, 255));
        jMin.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jMin.setForeground(new java.awt.Color(255, 255, 255));
        jMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMin.setText("-");
        jMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMinMouseExited(evt);
            }
        });

        jExt.setBackground(new java.awt.Color(255, 255, 255));
        jExt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jExt.setForeground(new java.awt.Color(255, 255, 255));
        jExt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExt.setText("X");
        jExt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jExt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jExtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jExtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jMin)
                .addGap(18, 18, 18)
                .addComponent(jExt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jExt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setIconFrame(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icon-logo.png")));
    }
    
    private void scrollBarUI(){
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());        
        jScrollPane1.setHorizontalScrollBar(sp);
    }
    
    private void dataKaryawan(){
        Object[] Baris ={"NIP","NAMA","JENIS KELAMIN","TGL LAHIR","NO. HANDPHONE","ALAMAT","JABATAN"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String sql = "SELECT * FROM karyawan ORDER BY nip ASC";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7)
                });
            }            
            tKaryawan.setModel(tabmode);            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Table Customer Failed!</b><br>"+e+"</p></html>","Table Customer Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }
    }
    
    private void reset(){
        tSearch.setText("Search...");
        dataKaryawan();
    }
    
    private void cariData(){
        String keyword = tSearch.getText();
        Object[] Baris ={"NIP","NAMA","JENIS KELAMIN","TGL LAHIR","NO. HANDPHONE","ALAMAT","JABATAN"};
        tabmode = new DefaultTableModel(null, Baris);
        try {
            String sql = "SELECT * FROM karyawan WHERE nip LIKE '%"+keyword+"%' or nama LIKE '%"+keyword+"%' or alamat LIKE '%"+keyword+"%' or jabatan LIKE '%"+keyword+"%'";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7)
                });
            }
            tKaryawan.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"<html><p style=\"font-size:11px; width:200px;\"><b style=\"font-size:14px;\">Failed!</b><br>"+e+"</p></html>","Failed!",JOptionPane.ERROR_MESSAGE,iconError);
        }                   
    }
    
    private void tablePopUpKaryawan(){
        int row = tKaryawan.getSelectedRow(); 
        String nip = tabmode.getValueAt(row, 0).toString();        
        String nm = tabmode.getValueAt(row, 1).toString();
        String jbtn = tabmode.getValueAt(row, 6).toString();        
        penilaian.pNip = nip;
        penilaian.pNk = nm;
        penilaian.pJbtn = jbtn;        
        penilaian.customerTerpilih();
        this.dispose();
    }
    
    private void tSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSearchFocusGained
        // TODO add your handling code here:
        if(tSearch.getText().equals("Search...")){
            tSearch.setText("");
            tSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tSearchFocusGained

    private void tSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSearchFocusLost
        // TODO add your handling code here:
        if(tSearch.getText().equals("")){
            tSearch.setText("Search...");
            tSearch.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tSearchFocusLost

    private void tSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSearchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cariData();
        }
    }//GEN-LAST:event_tSearchKeyPressed

    private void iSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseClicked
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_iSearchMouseClicked

    private void iSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseEntered
        // TODO add your handling code here:
        pSearch.setBackground(new Color(219,13,0));
    }//GEN-LAST:event_iSearchMouseEntered

    private void iSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iSearchMouseExited
        // TODO add your handling code here:
        pSearch.setBackground(new Color(255,68,56));
    }//GEN-LAST:event_iSearchMouseExited

    private void jMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(PopUpDataKaryawan.ICONIFIED);
    }//GEN-LAST:event_jMinMouseClicked

    private void jMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseEntered
        // TODO add your handling code here:
        jMin.setForeground(Color.RED);
    }//GEN-LAST:event_jMinMouseEntered

    private void jMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinMouseExited
        // TODO add your handling code here:
        jMin.setForeground(Color.WHITE);
    }//GEN-LAST:event_jMinMouseExited

    private void jExtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jExtMouseClicked

    private void jExtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseEntered
        // TODO add your handling code here:
        jExt.setForeground(Color.RED);
    }//GEN-LAST:event_jExtMouseEntered

    private void jExtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExtMouseExited
        // TODO add your handling code here:
        jExt.setForeground(Color.WHITE);
    }//GEN-LAST:event_jExtMouseExited
 
    private void tKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKaryawanMouseClicked
        // TODO add your handling code here:
        tablePopUpKaryawan();
    }//GEN-LAST:event_tKaryawanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpDataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iSearch;
    private javax.swing.JLabel jExt;
    private javax.swing.JLabel jMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pS;
    private javax.swing.JPanel pSearch;
    private javax.swing.JTable tKaryawan;
    private javax.swing.JTextField tSearch;
    public javax.swing.JLabel txtPopUp;
    // End of variables declaration//GEN-END:variables
}
